version: '3.6'
services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    user: root
    volumes:
      - ./mosquitto/config/:/mosquitto/config/
      - ./mosquitto/log/:/mosquitto/log/
      - ./mosquitto/data/:/mosquitto/data/
    ports:
      - 1883:1883
      - 9001:9001  
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    command: --check-caps false
    ports: 
      - 1972
      - 52795:52773
      - 53773
    volumes:
      - ./:/irisdev/app
